# Microsoft Store AppX/MSIX configuration file
# For more information, see: https://pub.dev/packages/msix
display_name: Luminara AI
publisher_display_name: Luminara AI
identity_name: LuminaraAI.LuminaraAI
publisher: CN=2AF02F98-D5C1-4CE1-AAD4-4E357ED25785
version: 1.0.0.0
logo_path: assets/luminara_icon_app.png

capabilities:
  - internetClient

# self-signed certificate
certificate_path: D:\Nuget\test_certificate.pfx
certificate_password: SmartAi@1379